# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://orientrcu.org/"
languageCode = "en-AU"
title = "Đơn vị Nghiên cứu và Tư vấn Phương Đông"
googleAnalytics = "UA-65383716-4"

# Metadata
[params]
  author = "Orient RCU"
  description = "Đơn vị Nghiên cứu và Tư vấn Phương Đông"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "https://orientrcu.org/images/hero_bg2.jpg"
  title = "<ul>1. Khoa học</ul><ul>2. Trung thực</ul><ul>3. Hợp tác</ul><ul>4. Gắn kết</ul><ul>5. Toàn diện</ul>"
  description = ""

# Navigation section
[params.nav]
  mission = "Sứ mệnh"
  services = "Dịch vụ"
  team = "Đội ngũ"
  contact = "Liên hệ"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "mission"
    title = "Sứ mệnh"
    subtitle = "Cải thiện chất lượng chăm sóc sức khoẻ người dân Việt thông qua nghiên cứu và phát triển nghiên cứu trong cộng đồng y tế Việt Nam."
    description = ""

  [[params.mission.item]]
    weight = 2
    name = "vision"
    title = "Tầm nhìn"
    subtitle = "<p>Phát triển một cộng đồng vững mạnh được xây dựng trên nền tảng khoa học.</p><p>Mang những giá trị của nghiên cứu khoa học đến gần hơn với cuộc sống đời thường</p>"
    description = ""

  [[params.mission.item]]
    weight = 3
    name = "objective"
    title = "Mục tiêu"
    subtitle = "Thiết lập và nhân rộng mô hình nghiên cứu khoa học tại bệnh viện và các cơ sở y tế trên cả nước."
    description = ""

# Services section
[params.services]
  enable = true
  video = false
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Dịch vụ của chúng tôi"
  description = "Chúng tôi cung cấp các dịch vụ tư vấn, đào tạo và tổ chức thực hiện nghiên cứu khoa học và phân tích dữ liệu, đặc biệt là trong lĩnh vực y sinh."

 [[params.services.item]]
    icon = "icon-present"
    title = "Đào tạo"
    description = "Cho tổ chức và cá nhân về: tổ chức phòng nghiên cứu khoa học tại cơ sở, kỹ năng thiết yếu trong thực hiện nghiên cứu cho nhân viên y tế, ngoại ngữ và kỹ năng phát triển sản phẩm nghiên cứu."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Tư vấn"
    description = "Cho cá nhân và tổ chức về: hoạt động nghiên cứu, phát triển phòng nghiên cứu, câu lạc bộ sinh hoạt nghiên cứu, tiếng Anh trong nghiên cứu, tổ chức phòng xét nghiệm, tổ chức hội nghị khoa học."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Tổ chức thực hiện nghiên cứu khoa học"
    description = "Thực hiện và hợp tác thực hiện nghiên cứu trong nước và quốc tế, kể cả nghiên cứu thị trường trong lĩnh vực dược phẩm và y sinh học, công nghệ và dịch vụ liên quan đến cộng đồng."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Phân tích dữ liệu"
    description = "Thực hiện phân tích dữ liệu và/hoặc đào tạo chuyên gia phân tích dữ liệu tại cơ sở, từ đó hỗ trợ các đơn vị trong chiến lược marketing và tiếp cận khách hàng tiềm năng, cũng như phát triển và định hướng nghiên cứu tại cơ sở."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Thực hành y tế toàn cầu"
    description = "Chúng tôi hợp tác hướng dẫn sinh viên trong nước và quốc tế về y tế toàn cầu và y tế công cộng."

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Đội ngũ vận hành"
  description = ""

  [[params.team.item]]
    name = "Lê Thị Quỳnh Nhi, TS"
    position = "Chủ tịch Hội đồng thành viên"
    description = ""
    img = "https://orientrcu.org/images/NhiLTQ2.jpg"

  [[params.team.item]]
    name = "Huỳnh Phạm Thu Hiền, BS"
    position = "Giám đốc tổ chức"
    description = ""
    img = "https://orientrcu.org/images/HienHPT2.jpg"


  [[params.team.item]]
    name = "Phùng Khánh Lâm, BS, TS"
    position = "Giám đốc chuyên môn"
    description = ""
    img = "https://orientrcu.org/images/LamPK2.jpg"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   email = "#"
  #   telephone = "#"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"
  #   whatsapp = "#"

# Contact section
[params.contact]
  enable = true
  title = "Liên hệ"
  message = "Email cho chúng tôi theo địa chỉ orient.rcu@gmail.com hoặc gửi lời nhắn ngay lập tức cho chúng tôi bằng cách điền thông tin vào các mục dưới đây:"
  name_placeholder = "Họ và tên"
  email_placeholder = "Địa chỉ email"
  email_disclaimer = "Thông tin về email của bạn sẽ được bảo mật."
  message_placeholder = "Nội dung lời nhắn."
  button_text = "Gửi"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2019 Bản quyền thuộc Đơn vị Nghiên cứu và Tư vấn Phương Đông.</p>"

  
